name: Print Machine Name and Hello World

on: [push]

jobs:
  say-hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print machine name and message
        run: |
          echo "Machine name: $(hostname)"
          echo "Hello, world!"

